# Generated by Django 4.2.5 on 2024-01-11 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_customuser_is_staff'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
