# Generated by Django 4.2.5 on 2023-11-15 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(default='defaultnews.jpg', upload_to='pages/news_images')),
                ('title', models.TextField(default='title')),
                ('text', models.TextField(default='text')),
            ],
        ),
    ]
