# Generated by Django 4.2.5 on 2023-11-15 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_news_date_crated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='date_crated',
            new_name='date_created',
        ),
    ]
