# Generated by Django 4.2.5 on 2023-12-08 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_rename_date_crated_news_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='photo',
            field=models.ImageField(default='news_default.jpg', upload_to='news_images/'),
        ),
    ]
