# Generated by Django 4.2.5 on 2023-11-14 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('finish_date', models.DateField()),
                ('reservation_status', models.CharField(choices=[('active', 'Aktywna'), ('canceled', 'Anulowana'), ('completed', 'Zakończona')], default='active', max_length=10)),
            ],
        ),
    ]
