# Generated by Django 4.2.5 on 2023-11-14 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(default='default.jpg', upload_to='cars/car_images')),
                ('brand', models.TextField(default='Marka')),
                ('model', models.TextField(default='Model')),
                ('air_conditioning', models.CharField(choices=[('YES', 'Tak'), ('NO', 'Nie')], default='YES', max_length=3)),
                ('doors_quantity', models.CharField(choices=[('TWO', '2'), ('THR', '3'), ('FOU', '4'), ('FIV', '5')], default='FIV', max_length=3)),
                ('people_quantity', models.IntegerField()),
                ('fuel_type', models.CharField(choices=[('GAS', 'Benzyna'), ('DIE', 'Diesel'), ('LPG', 'LPG'), ('ELE', 'Elektryczny')], default='GAS', max_length=3)),
                ('transmission_type', models.CharField(choices=[('A', 'Automatyczna'), ('M', 'Manualna')], default='M', max_length=3)),
                ('description', models.TextField(default='Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='CarType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='Kategoria')),
                ('description', models.TextField(default='Opis')),
            ],
        ),
    ]
