# Generated by Django 4.2.5 on 2023-12-08 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_car_car_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='photo',
            field=models.ImageField(default='cars_default.jpg', upload_to='car_images/'),
        ),
    ]
